version: '3.1'

services:
  postgresql:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_DB: todo_rist_development
      POSTGRES_USER: todo_rist
      POSTGRES_PASSWORD: todo_rist
    ports:
      - '5433:5432'
    volumes:
      - ${HOME}/docker/data/postgresql:/var/lib/postgresql/data
