version: '3.1'

services:
  postgresql:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_DB: techsum_development
      POSTGRES_USER: techsum
      POSTGRES_PASSWORD: techsum
    ports:
      - '5433:5432'
    volumes:
      - ${HOME}/docker/data/postgresql:/var/lib/postgresql/data
