---
name: thor
version: '1.2'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 20e6e0f0685139dbd29df50e03367e222aa5d1b8
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
