---
engine_version: 0.4.23
file_version: 2024-01-04 14:31:22.796150000 Z
resources:
- name: good_job/base_execution
  preferences:
    visible: false
  updated_at: 2023-12-17 15:42:15.575826000 +09:00
- name: good_job/batch_record
  preferences:
    visible: false
  updated_at: 2023-12-17 15:42:28.226904000 +09:00
- name: good_job/discrete_execution
  preferences:
    visible: false
  updated_at: 2023-12-17 15:42:29.827792000 +09:00
- name: good_job/execution
  preferences:
    visible: false
  updated_at: 2023-12-17 15:42:31.194642000 +09:00
- name: good_job/job
  preferences:
    visible: false
  updated_at: 2023-12-17 15:42:32.184724000 +09:00
- name: good_job/process
  preferences:
    visible: false
  updated_at: 2023-12-17 15:42:33.154181000 +09:00
- name: good_job/setting
  preferences:
    visible: false
  updated_at: 2023-12-17 15:42:34.068539000 +09:00
- name: link
  preferences:
    actions:
    - name: scrap
      display_name: Scrap
      action_type: method
      preferences:
        method_name: scrap_now
        show_on_table: true
    - action_type: form
      preferences:
        form_id: 1
      name: create
    columns:
    - access_type: hidden
      name: sanitized_url
  updated_at: 2023-12-21 20:46:06.190648000 +09:00
- name: user
  preferences:
    columns:
    - access_type: hidden
      name: uid
    - access_type: hidden
      name: image
    - access_type: hidden
      name: sign_in_count
    - access_type: hidden
      name: current_sign_in_at
    - access_type: hidden
      name: last_sign_in_at
    - access_type: hidden
      name: current_sign_in_ip
    - access_type: hidden
      name: last_sign_in_ip
    - name: password
      display_name: Password
      column_type: string
      access_type: hidden
      virtual: true
      validators: []
  updated_at: 2023-12-17 15:44:52.340243000 +09:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2023-12-26 00:17:49.611350000 +09:00
- key: resources.link.scopes.order
  value:
  - initial
  - summarizing
  - completed
  - failed
  - not_initial
  - not_summarizing
  - not_completed
  - not_failed
  - kept
  - discarded
  - undiscarded
  - with_discarded
  updated_at: 2023-12-17 15:46:45.684407000 +09:00
- key: resources.order
  value:
  - user
  - link
  - good_job/base_execution
  - good_job/batch_record
  - good_job/discrete_execution
  - good_job/execution
  - good_job/job
  - good_job/process
  - good_job/setting
  updated_at: 2023-12-17 15:42:03.340498000 +09:00
queries: []
dashboards: []
forms:
- id: 1
  name: Create Initial Link
  http_method: POST
  api_path: "/admin/links/initial"
  description:
  preferences:
    fields:
    - name: user_id
      display_name: User
      default_value:
      field_type: reference
      validators:
      - required: true
      reference:
        model_name: user
    - name: url
      display_name: URL
      default_value:
      field_type: input
      is_array: false
      validators:
      - required: true
    - display_name: date date
      name: date_date
      field_type: date
      default_value: ''
      validators: []
      is_array: false
    request_type: rest
  api_config_name: origin
  tags: []
  updated_at: 2024-01-04 23:31:22.796150000 +09:00
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2023-12-26 00:17:49.623339000 +09:00
