chrome_extension:
  id: oojfapnijkmanlpbpgmpbihdadedaimm
tos:
  url: https://electric-pine-1d7.notion.site/2024-03-04-390e0a023ffb425587ca615ab36b9b59?pvs=4
privacy_policy:
  url: https://electric-pine-1d7.notion.site/2024-03-04-096f6a7906eb4c68b558f6157a7c09f3?pvs=4
