class OpenAIClient
  MODEL : string

  @client: untyped

  def self.instance: () -> self

  def call_function: (content: string, functions: Array[function]) -> Array[result]
end

type function = {
    name: string,
    descrpiton: string,
    parameters: Hash[Symbol, parameter],
    required: Array[string]
  }

type parameter = { type: string, description: string }

type result = { name: string, arguments: Hash[Symbol, string] }
