name: Upload badge

description: Upload badge to gh-pages
runs:
  using: composite
  steps:
    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        clean: false
    - name: Upload badge
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "action@users.noreply.github.com"
        git add coverage
        git commit -m "Upload badge"
        git push
    - name: Checkout Back
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
