name: Upload badge

description: Upload badge to gh-pages
runs:
  using: composite
  steps:
    - name: stash
      shell: bash
      run: |
          git stash --include-untracked
    - uses: actions/checkout@v3
      with:
        clean: false
        ref: gh-pages
    - name: Upload badge
      shell: bash
      run: |
        rm -rf coverage
        git stash pop
        git config --global user.name "GitHub Actions"
        git config --global user.email "no-ye@users.noreply.github.com"
        git add coverage
        git commit -m "Upload badge"
        git push
    - name: Checkout Back
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
